### PR TITLE
Added Altivec subnormal (denormalized) value handler.

### PR DESCRIPTION
**Pull request by dmiller423**
This replicates the SSE code on Altivec,  Flush to Zero is done via writing to vscr register and setting non-ieee mode.

### CODE REVIEW

**Comment by jlost** [comment]
#43 
Testing this soon.

**Comment by jlost** [comment]
That fixed the problem for me, thanks!

**Comment by dmiller423** [comment]
👍

**Comment by martinvandriel** [comment]
I think this could be merged. Objections? @sstaehler

**Comment by sstaehler** [comment]
No, please go ahead!

**Pull request merged**
